// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBacTCgeQjMWWkJMF5G4IGSYsKsSodiqqg',
    appId: '1:477695915084:web:c47addee4e11d18bbd70e9',
    messagingSenderId: '477695915084',
    projectId: 'chatapp-3e464',
    authDomain: 'chatapp-3e464.firebaseapp.com',
    storageBucket: 'chatapp-3e464.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyMQH0wgvX6RMSb0DJATgM50P6aHvBf0A',
    appId: '1:477695915084:android:6f615a596ad39a20bd70e9',
    messagingSenderId: '477695915084',
    projectId: 'chatapp-3e464',
    storageBucket: 'chatapp-3e464.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbqid4uHmmWwuuYawyZlgwJCwz-cxLa1w',
    appId: '1:477695915084:ios:c2f467739d0ce413bd70e9',
    messagingSenderId: '477695915084',
    projectId: 'chatapp-3e464',
    storageBucket: 'chatapp-3e464.appspot.com',
    iosBundleId: 'com.example.task04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbqid4uHmmWwuuYawyZlgwJCwz-cxLa1w',
    appId: '1:477695915084:ios:c2f467739d0ce413bd70e9',
    messagingSenderId: '477695915084',
    projectId: 'chatapp-3e464',
    storageBucket: 'chatapp-3e464.appspot.com',
    iosBundleId: 'com.example.task04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBacTCgeQjMWWkJMF5G4IGSYsKsSodiqqg',
    appId: '1:477695915084:web:84e4ad47cdc71c6cbd70e9',
    messagingSenderId: '477695915084',
    projectId: 'chatapp-3e464',
    authDomain: 'chatapp-3e464.firebaseapp.com',
    storageBucket: 'chatapp-3e464.appspot.com',
  );
}
